ged/ruby-pg

- ext/extconf.rb
- ext/pg_binary_decoder.c
- ext/pg_binary_encoder.c
- ext/pg_text_decoder.c
- ext/pg_text_encoder.c
- ext/pg_type_map.c
- ext/pg_type_map_by_column.c
- inttypes.h is not available in MSVC 2008
- Structs members must be initialized implicitly
> Fixing compilation problems with Microsoft Visual Studio 2008.

- Rakefile.cross
I updated OpenSSL version `1.0.2f` from `1.0.2e` because `OpenSSL 1.0.2e` is disappeared.
After this pull request is merged, a failed pull request, https://github.com/ged/ruby-pg/pull/12, and other pull requests will be passed.
> update version OpenSSL

- README.rdoc
Since Ruby 2.3.0 and Ruby 2.4 was released, I added it.
However, I do not understand well that the following points.
In this repository, there are mixed descriptions that can be read as Ruby 2.0 and Ruby 2.2.
examples:
- Bitbucket(Home): [Ruby 2.0 or newer](https://bitbucket.org/ged/ruby-pg/wiki/Home#markdown-header-requirements)
- GitHub(README): [Ruby 2.2](https://github.com/ged/ruby-pg/blob/master/README.rdoc#requirements)  
- .travis.yml: [Ruby 2.2, 2.3.0 tested](https://github.com/ged/ruby-pg/blob/fa0f29affc8eb850ee9ddb972a46ade7fc32195e/.travis.yml#L6-L7)
- pg.gemspec: [Ruby 2.0.0 required](https://github.com/ged/ruby-pg/blob/fa0f29affc8eb850ee9ddb972a46ade7fc32195e/pg.gemspec#L22)
I speculated "Ruby 2.2 or newer" from the below change
- …
> Add notation Ruby 2.2 "or newer"

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
Previously the code checked if the argument
contained an URI instead of being one. This
caused some connection strings being mis-
dected as connection URI's.
fixes #265  ( https://bitbucket.org/ged/ruby-pg/issues/265/colon-not-allowed-in-a-connection-string )
> Check if the argument for #Connection is an URI

- spec/helpers.rb
Hi,
I am working for this `ruby-pg`'s RPM package on Fedora Project [1] and Red Hat.
I have to build your package on very long path working directory (`/builddir/build/BUILD/pg-0.21.0/opt/rh/rh-ruby25/root/usr/share/gems/gems/pg-0.21.0`) because of our build system.
And that causes PostgreSQL failed to start.
Below is the `setup.log` log file.
```
$ cat tmp_test_specs/setup.log
...
pg_ctl -D /builddir/build/BUILD/pg-0.21.0/opt/rh/rh-ruby25/root/usr/share/gems/gems/pg-0.21.0/tmp_test_specs/data -l logfile start
waiting for server to start....LOG:  Unix-domain socket path "/builddir/build/BUILD/pg-0.21.0/opt/rh/rh-ruby25/root/usr/share/gems/gems/pg-0.21.0/tmp_test_specs/.s.PGSQL.54321" is too long (maximum 107 bytes)
```
So, I want to specify the test directory by environment variable.
If …
> Specify test directory by environment variable.

- ext/extconf.rb
- ext/pg_text_decoder.c
- lib/pg/text_decoder.rb
This moves PG::SimpleDecoder::TimestampWithTimeZone and PG::SimpleDecoder::TimestampWithoutTimeZone to C. It is based on https://github.com/ged/ruby-pg/pull/19 with some tweaking by me.
I tested the implementation successfully on Windows-10 with MINGW (RubyInstaller), Ubuntu-18.04 with glibc, Alpine-Linux-3.7 with musl-libc and Android-7.0 with bionic-libc (termux).
The conversion is done by a fast path and as a fallback by a slower path. The slow path is used under these conditions:
* `timegm()` is not available (on Windows)
* `RUBY_VERSION < 2.3.0` (it doesn't provide `rb_time_timespec_new()`)
* time conversion by `timegm()` or `mktime()` fails at runtime (happens on Android)
I did some very simple benchmarks with the following results:
```
ruby -Ilib -rpg -e …
```
> Faster time decoder

- ext/pg_text_decoder.c
- spec/pg/basic_type_mapping_spec.rb
I found these issues by porting the code to sequel_pg and running
Sequel's tests.
It turns out that IPAddr doesn't support non-zero parts after the
netmask, such as 1.2.3.4/24, and automatically modifies the part
after the netmask to be 0 (turning 1.2.3.4/24 to 1.2.3.0/24).
Because the default is to set instance variables for performance,
this resulted in the creation of IPAddr instances that you could
not generate using IPAddr's public API.  To fix that, mask the
part of the IP address integer(s) before calling UINT2NUM or
ULL2NUM.
I've modified the inet tests to be much simpler, just checking
that the returned value for the inet column matches what you
would get if you parsed the input string with IPAddr.new. I've
also added tests for the above issue.
Modifying the passed in char* …
> Fix various issues in the inet/cidr decoder

- ext/pg.c
- ext/pg.h
`rb_encdb`-prefixed functions are only for internal use.
use `rb_enc_alias` instead.
> Use rb_enc_alias

- spec/pg/basic_type_mapping_spec.rb
- spec/pg/type_spec.rb
Ruby and PostgreSQL seem to have a different opinion about the right timezone to be applied to BC dates in some countries. Therefore verify the timestamp without timezone.
This failed for @ged like so:
1) Basic type mapping PG::BasicTypeMapForResults connection wide type mapping should convert format 0 timestamps with time zone
Failure/Error: expect( res.getvalue(0,2).iso8601(3) ).to eq( Time.new(-4713, 11, 24, 23, 58, 59.1231, "-03:00").getlocal.iso8601(3) )
expected: "-4713-11-24T18:58:59.123-08:00"
got: "-4713-11-24T19:06:01.123-07:52"
(compared using ==)
: # ./spec/pg/basic_type_mapping_spec.rb:261:in `block (5 levels) in <top (required)>'
: # ./spec/helpers.rb:29:in `block in included'
> Ignore timeshift for BC timestamp.

- .travis.yml
- spec/helpers.rb
- spec/pg/connection_spec.rb
Hello,
I want to add a feature to set testing port, because in my environment (Fedora project's build environment), I can not use the standard port.
Ref: https://bitbucket.org/ged/ruby-pg/issues/283
> Add feature to set testing port.

- lib/pg/connection.rb
Maybe this PR fixes below issue.
https://bitbucket.org/ged/ruby-pg/issues/286/warning-uriregexp-is-obsolete
As a default behavior of the testing command, there are messages for the stdout and stderr like this.
This situation makes us harder to find a real warning issue like this issue.
I think we can suppress the outputted message as much as possible except "..." by RSpec as a default behavior of `rake test`.
The messages could be outputted to `tmp_test_specs/setup.log` or only `$VERBOSE` mode.
```
$ bundle exec rake test
...
Setting up test database for Basic type mapping
Creating the test DB
Warning: no type cast defined for type "name" with oid 19. Please cast this type explicitly to TEXT to be safe for future changes.
Warning: no type cast defined for type "regproc" with oid 24. …
```
> Suppress "warning: URI.regexp is obsolete".

- lib/pg/basic_type_mapping.rb
- spec/pg/basic_type_mapping_spec.rb
This PR is to suppress unnecessary warnings in the testing result.
https://github.com/ged/ruby-pg/pull/35#issue-267538593
> As a default behavior of the testing command, there are messages for the stdout and stderr like this.
This situation makes us harder to find a real warning issue like this issue.
`STDERR` does not work. It is not captured by the RSpec stderr testing method.
But `$stderr` works.
According to rubocop style guide, `$stderr` is recommended rather than `STDERR`.
https://github.com/rubocop-hq/ruby-style-guide
> Use $stdout/$stderr/$stdin instead of STDOUT/STDERR/STDIN. STDOUT/STDERR/STDIN are constants, and while you can actually reassign (possibly to redirect some stream) constants in Ruby, you'll get an interpreter warning if you do so.
> Add a test to check a content of the warning.

- spec/helpers.rb
- spec/pg/connection_spec.rb
Suppress warnings part 2.
Use ruby -w or rspec -w to see the trace log.
trace log is outputted when `$VERBOSE` is true.
When we want to show the trace log, we can show it like this.
```
$ bundle exec rspec -w
```
or
```
$ bundle exec ruby -w -S rspec
```
or
spec/helpers.rb
```
RSpec.configure do |config|
..
config.warnings = true
..
end
```
Fix blow warnings shown at the top of the log.
```
/home/travis/build/ged/ruby-pg/spec/pg/connection_spec.rb:291: warning: already initialized constant EXPECTED_TRACE_OUTPUT
/home/travis/build/ged/ruby-pg/spec/pg/connection_spec.rb:291: warning: previous definition of EXPECTED_TRACE_OUTPUT was here
```
Now only 2 types of warnings: `WARNING:  there is no transaction in progress` and `WARNING:  there is already a transaction in progress` from somewhere …
> Suppress warnings.

- .travis.yml
- spec/env/Dockerfile.i386
This PR is to update Travis CI i386 case with new recommended way.
The used `multiarch/qemu-user-static` image is recommending new way to use not compatible "multiarch/*" arch image, but standard arch image
Ref: https://github.com/multiarch/qemu-user-static
Here is the Ubuntu standard i386 image.
https://hub.docker.com/_/ubuntu Supported architectures links "i386",
https://hub.docker.com/r/i386/ubuntu/
I added below line in `Dockerfile.i386` as I faced installed tzdata deb package asking interactive dialog during the process of the installation, seeing this URL https://askubuntu.com/questions/909277/avoiding-user-interaction-with-tzdata-when-installing-certbot-in-a-docker-contai .
```
+# To prevent installed tzdata deb package to show interactive dialog.
+ENV DEBIAN_FRONTEND …
```
> Change i386 case to use standard i386/ubuntu:bionic

- ext/pg.h
- ext/pg_result.c
Allocation of the ruby typed data object VALUE is now done within the function that assigns the PGresult retrieved from libpq. Therefore the data pointer of the PG::Result instance is always valid.
There's no need to check the 'this' pointer at every use any longer.
These 'this' pointer checks were introduced at commit de2487c928db6228a701074f4572f438284a717c, when we moved to a variable size data memory. This variable memory allows us to store the field_names once per PG::Result and reuse them several times. However this also moved the memory allocation out of PG::Result#allocate, so that we had to check for validity of the pointer.
This patch removes `PG::Result.allocate` and `PG::Result.new`, which is obvoiusly an API change. However although these methods were callable, the resulting …
> Ensure valid PG::Result data pointer

- README-Windows.rdoc
- README.ja.rdoc
- README.rdoc
- ext/pg.c
- misc/postgres/README.txt
- misc/ruby-pg/README.txt
Since Bitbucket is shutting down support for Mercurial, and most of the work is done via git nowadays, there’s no reason to keep ruby-pg there any longer.
> Change URLs to point to Github

- Manifest.txt
- ext/pg.c
- ext/pg.h
- ext/pg_record_coder.c
- ext/pg_row_coder.c
- lib/pg/basic_type_mapping.rb
- lib/pg/coder.rb
- spec/pg/basic_type_mapping_spec.rb
- spec/pg/type_spec.rb
This implements proper encoder and decoder for Composite Types as described in https://www.postgresql.org/docs/11/rowtypes.html and as requested in https://bitbucket.org/ged/ruby-pg/issues/258
This adds the following classes:
* PG::RecordCoder < PG::Coder
* PG::RecordEncoder < PG::RecordCoder
* PG::RecordDecoder < PG::RecordCoder
* PG::TextEncoder::Record < PG::RecordEncoder
* PG::TextDecoder::Record < PG::RecordDecoder
I first took `PG::RowCoder` as class name,  due to the `ROW(...)` expression provided by PostgreSQL. However this is changed in the second commit, since "Row" is too generic in my opinion and could lead to confusion with `CopyRow`. So I think "Record" expresses this type of data best. 
Unfortunately the names `PG::CompositeCoder`, `PG::CompositeDecoder` and …
> Add PG::RecordCoder for en/decoding of Composite Types

- ext/pg.h
- ext/pg_binary_decoder.c
- ext/pg_connection.c
- ext/pg_copy_coder.c
- ext/pg_record_coder.c
- ext/pg_result.c
- ext/pg_text_decoder.c
- ext/pg_tuple.c
The Ruby core team decided to deprecate the taint mechanism in Ruby 2.7
and will remove that in Ruby 3.
https://bugs.ruby-lang.org/issues/16131
https://github.com/ruby/ruby/pull/2476
In Ruby 2.7, `Object#{taint,untaint,trust,untrust}` and related
functions in the C-API no longer have an effect (all objects are always
considered untainted), and are now warned deprecation message.
https://buildkite.com/rails/rails/builds/65054#14bdbd8c-d935-4b80-8842-c81266a1a34e/6-8
> The taint mechanism will be deprecated in Ruby 2.7

- ext/extconf.rb
- ext/pg.c
- ext/pg_connection.c
- ext/pg_result.c
- spec/helpers.rb
- spec/pg/connection_spec.rb
- spec/pg/result_spec.rb
I noticed that there are some missing functions and constants regarding error messages.
This adds some new constants and:
* PG::Connection#set_error_context_visibility
* PG::Result#verbose_error_message
* PG::Result#result_verbose_error_message (alias)
> Add extended error message functions of PostgreSQL-9.6

- ext/pg_text_encoder.c
- lib/pg/text_encoder.rb
- spec/pg/type_spec.rb
Current `TextEncoder::Numeric` doesn't handle other classes than `BigDecimal`. That doesn't bother as long as `BasicTypeMapping` is used directly to encode values, since it selects the encoder based on the input type. However if a type map is generated by `PG::TypeMapByOid#build_column_map` or manually it fails on Integer and Float values. This is fixed with this PR.
This moves the conversion of  BigDecimal` to C, so that we can make use of our fast Integer and Float encoders. They avoid additional string allocations, which a ruby conversion would do.
Fixes #310
> Accept Integer and Float as input to TextEncoder::Numeric

- README.rdoc
This pull request removes the link to Bitbucket because https://bitbucket.org/ged/ruby-pg shows this message:
```
This repository has been deleted
Our apologies, but the repository "ged/ruby-pg" has been deleted.
It now lives at https://github.com/ged/ruby-pg.
```
> ruby-pg repository is only available at GitHub

- ext/pg_connection.c
- ext/pg_result.c
This drops documentation for PostgreSQL versions we no longer support.
> Remove old PostgreSQL version info from docs

- README.rdoc
- ext/pg_binary_decoder.c
- ext/pg_binary_encoder.c
- ext/pg_text_encoder.c
Ideally this should have the format of a table. Unfortunately rdoc doesn't supoort any kind of tables except in the markdown parser. However even the markdown parser supports tables only through raw HTML and doesn't do any automatic linking to internal classes.
I still think such an overview is very helpful for someone who wants to understand or use the type cast system:
Hope this can be in pg-1.2.0.
> Add an overview about coders and type maps to README

- ext/pg_result.c
This can be used by sequel_pg to get the encoding index, as discussed in https://github.com/jeremyevans/sequel_pg/issues/34.
I've prepared an update to sequel_pg to use this function:
```
$ ruby24 -I /data/code/external/ruby-pg/lib bin/sequel postgres:///?user=sequel_test -c 'p $LOADED_FEATURES.grep(/pg.*.so\z/); p DB[:s].get(:s)'
["/data/code/external/ruby-pg/lib/pg_ext.so", "/usr/local/lib/ruby/gems/2.4/gems/sequel_pg-1.12.2/lib/sequel_pg.so"]
"\xE1\x80\x80"
$ ruby24 -I /data/code/sequel_pg/lib -I /data/code/external/ruby-pg/lib bin/sequel postgres:///?user=sequel_test -c 'p $LOADED_FEATURES.grep(/pg.*.so\z/); p DB[:s].get(:s)'
["/data/code/external/ruby-pg/lib/pg_ext.so", "/data/code/sequel_pg/lib/sequel_pg.so"]
"\u1000"
```
I would appreciate it if pg 1.2.1 could be released with this …
> Add pg_get_result_enc_idx

- Rakefile.cross
`File.symlink()` raises `NotImplementedError` prior to MRI 2.3.
Fixes AppVeyor builds for `ruby_version=22`.
> Recognize symlink failure on old Ruby

- lib/pg/basic_type_mapping.rb
- spec/pg/basic_type_mapping_spec.rb
These columns are of text-like types (name, regproc) which are not mapped. Since they’re ultimately just treated as text, follow our own warning and cast them in SQL to avoid a Ruby type cast warning.
> Avoid type cast warning in build_coder_maps

- .travis.yml
- ext/extconf.rb
- ext/pg.h
- ext/pg_coder.c
- ext/pg_connection.c
- ext/pg_copy_coder.c
- ext/pg_record_coder.c
- ext/pg_result.c
- ext/pg_tuple.c
- ext/pg_type_map.c
- ext/pg_type_map_all_strings.c
- ext/pg_type_map_by_class.c
- ext/pg_type_map_by_column.c
- ext/pg_type_map_by_mri_type.c
- ext/pg_type_map_by_oid.c
- ext/pg_type_map_in_ruby.c
- spec/pg/gc_compact_spec.rb
- spec/pg/type_map_by_class_spec.rb
- spec/pg/type_map_by_column_spec.rb
- spec/pg/type_map_by_mri_type_spec.rb
- spec/pg/type_map_by_oid_spec.rb
The classic way to allocate T_DATA objects is deprecated since Ruby-2.0. The new way with rb_data_type_t structure has same advantages:
1. Type checks are more specific
2. C-ext can emit memory size information
3. C objects can be made GC.compact friendly
Currently [TruffleRuby fails in CI](https://travis-ci.org/github/larskanis/ruby-pg/jobs/715289488#L635), but the issue is fixed in https://github.com/oracle/truffleruby/commit/f460ce7998c4be937ad298ca3f0daac12d4531e2
This makes ruby-pg GC.compact friendly by reverting https://github.com/ged/ruby-pg/commit/7c1756f953e0c405fc0bf987d046c416e5bb061c but using the compactation callback. This hopefully improves performance as described in #343.
> Change all T_DATA objects to typed data

- README.rdoc
The example fails because the column names `procpid` and `current_query` are incorrect. The correct names are `pid` and `query`.
See: https://www.postgresql.org/docs/current/monitoring-stats.html#PG-STAT-ACTIVITY-VIEW
> Fix README example

- spec/pg/basic_type_mapping_spec.rb
I living in China which +8:00 timezone, there's a test case failure
```
1) Basic type mapping PG::BasicTypeMapForQueries should do default array-as-array param encoding with Time objects
Failure/Error: expect( res.values[0][0] ).to match( /\{\"2019-12-08 \d\d:38:12.123[+-]\d\d\"\}/ )
expected "{\"2019-12-09 05:38:12.123+08\"}" to match /\{\"2019-12-08 \d\d:38:12.123[+-]\d\d\"\}/
Diff:
@@ -1 +1 @@
-/\{\"2019-12-08 \d\d:38:12.123[+-]\d\d\"\}/
+"{\"2019-12-09 05:38:12.123+08\"}"
```
this PR should fix the test
> fix test time mapping fails on +800 timezone

- lib/pg/basic_type_mapping.rb
- spec/pg/basic_type_mapping_spec.rb
Redshift doesn't support OID these casts, so we do OID lookup through the pg_proc table and add type 'name' as an alias for 'text'.
Also clean up the type map generation, so that only arrays are separated and all other types can be registered.
Fixes #369
> Avoid casting of OIDs to fix compat with Redshift database

- Gemfile
- Rakefile
- appveyor.yml
- ext/extconf.rb
- lib/pg.rb
- misc/rake-compiler-make-install-patch.rb
- spec/pg_spec.rb
In ELF based systems the libpq path is stored as rpath in `pg_ext.so`, so that libpq is found, even if it's not in the library search paths.
On Windows however the rpath mechanism doesn't work and the search path for libpq had to be set added manually per `RUBY_DLL_PATH`. This is now automatically done per `RubyInstaller::Runtime.add_dll_directory`.
The libpq path is available in `extconf.rb` while build only (while gem install), so that we have to pass the string to lib/pg.rb where pg_ext.so is loaded (while `require 'pg'`). This is a bit tricky, since `pg_ext.so` is linked to libpq, so that the library search path has to be set first, prior to loading `pg_ext.so`.
Therefore a second file is needed bypassing `pg_ext.so`. That is `postgresql_lib_path.rb` and it is passed by mkmf's …
> Make the library path of libpq available in ruby and add it to the DLL search paths on Windows which lacks rpath.

- .appveyor.yml
- .github/workflows/binary-gems.yml
- .github/workflows/source-gem.yml
- .travis.yml
- Gemfile
- Rakefile
- appveyor.yml
- ext/extconf.rb
- lib/pg.rb
- misc/rake-compiler-make-install-patch.rb
- spec/pg_spec.rb
That way we can finally test if our binary windows gems run properly and if gem packaging works.
And this adds a run on Macos.
Also remove no longer necessary jobs from Appveyor and Travis-CI.
The first two commits are from #373. They allow to do Windows tests without setting `RUBY_DLL_PATH`.
Fixes #362
> Add Github Actions for tests of source gem and binary gems

- lib/pg/basic_type_mapping.rb
- spec/pg/basic_type_mapping_spec.rb
It has always been easy to register a binary encoder to PG::BasicTypeMapForQueries like so:
```ruby
class BinaryData < String; end
tm[BinaryData] = PG::BinaryEncoder::Bytea.new
```
However it might be more convenient to add a default class that can be used without registration.
Related to #344
> Add PG::BasicTypeMapForQueries::BinaryData for encoding of bytea columns

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
It's the intention of a transaction to rollback all queries anyway and there's no use in keeping the query running any longer.
Previously the rollback could be delayed until the latest query in the transaction finished, if the rollback was caused by a ruby exception or signal like Ctrl-C.
Fixes #390
/cc @thatsmydoing
> Cancel a possibly running query before a transaction is rolled back

- ext/pg.h
- ext/pg_coder.c
- ext/pg_connection.c
- ext/pg_copy_coder.c
- ext/pg_record_coder.c
- ext/pg_result.c
- ext/pg_tuple.c
- ext/pg_type_map.c
- ext/pg_type_map_all_strings.c
- ext/pg_type_map_by_class.c
- ext/pg_type_map_by_column.c
- ext/pg_type_map_by_mri_type.c
- ext/pg_type_map_by_oid.c
- ext/pg_type_map_in_ruby.c
- spec/helpers.rb
- spec/pg/connection_spec.rb
- spec/pg/gc_compact_spec.rb
- spec/pg/type_map_by_class_spec.rb
- spec/pg/type_map_by_column_spec.rb
- spec/pg/type_map_by_mri_type_spec.rb
- spec/pg/type_map_by_oid_spec.rb
- spec/pg/type_map_in_ruby_spec.rb
- spec/pg/type_map_spec.rb
- spec/pg/type_spec.rb
This merges improvements of #377, adds tests of new memsize functions and improves function signature verification by the compiler.
> Add memsize callbacks and improve callback definition

- ext/pg.h
- ext/pg_coder.c
- ext/pg_connection.c
- ext/pg_copy_coder.c
- ext/pg_record_coder.c
- ext/pg_type_map.c
- ext/pg_type_map_all_strings.c
- ext/pg_type_map_by_class.c
- ext/pg_type_map_by_column.c
- ext/pg_type_map_by_mri_type.c
- ext/pg_type_map_by_oid.c
- ext/pg_type_map_in_ruby.c
This is a followup of #349
1. ruby macro for default `dfree` is used
2. added functions for `dsize`
3. added missing mark functions
> Add dsize functions to typed data and use a ruby macro for default dfree

- lib/pg/basic_type_mapping.rb
- spec/pg/basic_type_mapping_spec.rb
Please see individual commits for extensive details. I’m happy to separate into multiple PRs if some work needs more vetting or discussion, as each commit can stand on its own (but separating will require resolving conflicts as commits 2 & 3 both depend on 1).
This is the result of investigation after encountering some performance issues with type map initialization being unexpectedly slow (after implementing a more time-sensitive use case) when the number of rows queries from `pg_type` is quite large (~131k in production). The enclosed performance testing was done on in an ideal (and faster) development environment with similar schema and slightly large pg_type set (~189k). In our production environment we were seeing type map creation take 4,102±550 ms, and since we create two type …
> Improve performance of type map creation

- pg.gemspec
These don't render on https://rubygems.org/gems/pg and the gemspec spec 
specifies they should not include examples or formatting: 
- https://guides.rubygems.org/specification-reference/#description
> Don't use markup in gemspec description & summary

- ext/pg_result.c
This fixes a few typos and such in the `PG::Result` docs
> Fix some typos and such

- README.rdoc
- Re-order CI badges:
- from: Travis CI (.org) --> AppVeyor --> GitHub Actions
- to: GitHub Actions --> AppVeyor --> Travis CI (.com)
Supersedes #406
Follows up #374
Signed-off-by: Takuya Noguchi <takninnovationresearch@gmail.com>
> Update CI status badges around Travis CI

- .github/workflows/source-gem.yml
- ext/extconf.rb
- ext/pg.c
- ext/pg_connection.c
- ext/pg_result.c
- spec/helpers.rb
- spec/pg/connection_spec.rb
> Add support for pipeline mode of PostgreSQL-14

- README.rdoc
I found that the link to clog file on README is broken on GitHub.
It indicates to `https://github_com/***/History_rdoc.html` instead of `https://github.com/***/History_rdoc` .
This can be fixed by changing the URL to [local file links](https://docs.ruby-lang.org/en/2.1.0/RDoc/Markup.html#class-RDoc::Markup-label-Links) on RDoc.
But I'm not sure this is the best way to handle this problem because I don't know how README is used on other places.
I would be grateful if you could give me an advice.
Thank you.
> [RFC] Change clog link on README to relative path

- ext/extconf.rb
- ext/pg_connection.c
It is based on the code that was removed in commit https://github.com/ged/ruby-pg/pull/397/commits/6c885e8ba0b2f0f83d0476c186d69aa88ee7e2c4
Fixes #416
CC: @jirubio
> Add a faster Windows specific `rb_io_wait()` implementation

- ext/pg_connection.c
This fixes a regression in pg 1.3.0 where the `pg_rb_io_wait` compatibility shim for Ruby 2.x drops fractional seconds. This results in `wait_socket_readable` waiting only whole seconds and busy-looping any remaining fractional seconds for every wait. Waits below 1000 ms will exclusively busy-loop.
This can be reproduced with the following test script:
```ruby
require 'pg'
require 'benchmark'
connection = PG::Connection.new
bm = Benchmark.measure do
connection.wait_for_notify(1.5)
end
p bm.total.round(3)
```
The output on Ruby 2.7 will show ~0.5 seconds of CPU usage without this fix when it should be ~0.0 seconds. Ruby 3.x is unaffected.
> Fix high CPU usage when waiting with a timeout on Ruby < 3.0

- ext/pg_type_map_all_strings.c
- ext/pg_type_map_by_column.c
- spec/pg/type_map_by_column_spec.rb
- spec/pg/type_spec.rb
The COPY and record decoders use a ruby string as internal buffer. If this buffer is given to the user, it must be passed through `rb_str_modify()`.
Fixes #427
> Fix String objects with non-applied encoding

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
This avoids sending a cancel request if there is no active query running.
In case of a failing SQL statement, the transaction_status is PQTRANS_INERROR. The previous code sent a cancel request in this case although the query is known to be aborted.
In case of ruby code that raised an error, the transaction_status is PQTRANS_INTRANS. Also in this case there is no use of sending a cancel request.
The cancellation of queries in case of exceptions was introduced by #391 . Now we cancel more conservative, only in case of a running query.
The cancellation can cause issues with pgbouncer, which releases a connection after a SQL error was raised.
It then dispatched the cancel to the next SQL command. This change should solve this incompatibility.
Fixes #430
> Cancel only active query after failing transaction

- ext/pg_tuple.c
Object flags are pretty internal information so we shouldn't be checking
them (if possible).  In this case, we don't need to check the status of
EXIVAR because `rb_copy_generic_ivar` will check the flag and return if
there are no ivars to copy[1] and will set the flag on the cloned object
if it did copy[2]
Just for some background, `FL_EXIVAR` flag indicates that an object has
instance variables, but only objects that are not of the type
`T_OBJECT`, `T_CLASS`, or `T_MODULE`.  This type of knowledge is really an
implementation detail, so I think C extensions should not know it or use
it.
1. https://github.com/ruby/ruby/blob/24909f5b3de10b6f0b6f9acbf44ed347ccabb7e7/variable.c#L1725-L1727
2. https://github.com/ruby/ruby/blob/24909f5b3de10b6f0b6f9acbf44ed347ccabb7e7/variable.c#L1741
> Remove FL_TEST and FL_SET

- ext/pg_connection.c
- lib/pg/connection.rb
- sample/async_api.rb
- spec/helpers/tcp_gate_scheduler.rb
- spec/pg/connection_spec.rb
The file_no of the socket IO can change while connecting. This can happen when alternative hosts are tried,
while GSS authentication and when falling back to unencrypted in `sslmode:prefer` . Therefore expire the socket IO at each `connect_poll` and `reset_poll` call.
Caching the IO previosly led to occasional errors kind of:
`Errno::EBADF: Bad file descriptor`
> Don't cache the socket-IO while connection setup

- lib/pg/connection.rb
Previously it was kept open until the PG::Connection was garbage collected.
Fixes #439
> Don't leak IO in case of connection error

- ext/pg_result.c
sequel_pg needs to do its own typecasting and column name mangling,
and can do so by passing data through using a void *.  This should
not affect existing ruby-pg usage, and I expect the performance
difference is not even measurable.
This can help sequel_pg work around the performance decrease when
using set_single_row_mode (#442).
> Allow pgresult_stream_any to be used by sequel_pg

- ext/pg_connection.c
- spec/pg/connection_spec.rb
conn.block still reads data from the socket, but only after checking the result queue and waiting for readability first. Reading data from the socket (PQconsumeInput) takes much more time than just checking available results (PQisBusy). So doing it as a precaution to conn.block is a performance issue, now that we call block before each get_result in pg-1.3.x.
The test was introduced in commit 09bdc1644a373fb641851a28171d193af028f6a0 . It is not particular specific to conn.block, so that we can check the error class on consume_input equaly.
Fixes #442
> Don't read from socket when data is pending in conn.block

- ext/pg_result.c
Fixes usage when trying to stream the result of a procedure
call that returns no results.
Fixes Sequel tests when Sequel is set to stream all results.
Here's a reproducer that just uses ruby-pg without Sequel:
```ruby
require 'pg'
conn = PG::Connection.new(user: "sequel_test")
conn.exec(<<END)
CREATE TABLE posts (a INTEGER);
CREATE OR REPLACE PROCEDURE test_procedure_posts()
LANGUAGE SQL
AS $$
INSERT INTO posts VALUES (1) RETURNING *;
INSERT INTO posts VALUES (2) RETURNING *;
SELECT max(posts.a), min(posts.a) FROM posts;
$$;
END
at_exit{conn.exec("DROP PROCEDURE test_procedure_posts(); DROP TABLE posts;")}
conn.send_query("CALL test_procedure_posts();")
conn.set_single_row_mode
conn.get_result.stream_each do |res|
p [__LINE__, res]
end
conn.block
conn.send_query("CALL …
```
> Handle PGRES_COMMAND_OK in pgresult_stream_any

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
During #copy_data for output, if an exception is raised after consuming all the
data from get_copy_data, then the subsequent cleanup triggers a "no COPY in
progress" error when it tries to call get_copy_data again, which causes the
original exception to be lost.
Fix by ignoring PG::Error during get_copy_data cleanup.
> Handle client error after all data consumed in #copy_data for output

- lib/pg.rb
- lib/pg/connection.rb
There is no reason to use **kwargs in either of these methods,
as connect_start doesn't handle keywords (keywords passed to it
will be treated as a positional hash).
Fixes deprecation warning when using Sequel's postgres adapter in
Ruby 2.7.
> Avoid spurious keyword argument warning on Ruby 2.7

- ext/pg_connection.c
- lib/pg/connection.rb
- spec/pg/connection_spec.rb
This better mimics, what libpq does internally.
`put_copy_data` is significantly faster when it doesn't `flush` at every call. This is by a factor of 4 on Linux and 10 on Windows when sending typical per-row blocks of 60 byte.
`put_copy_end` unconditionally calls `flush` in libpq, so it is not changed here.
Also adjust `conn.block` to send all enqueued data to mimic the behavior of `get_result` in libpq. With the change to `put_copy_data`, unsent data can happen, when largs blocks are sent. In this case `get_result` should catch up on flush. This is what the newly added spec verifies.
`PQgetResult` does flushing based on it's internal states that we don't have access to. Since `conn.block` is performance critical in case of `single_row_mode`, we don't flush at every call to `conn.block`, …
> Don't flush at each put_copy_data call, but flush at get_result

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
Having a return/break inside the Connection#transaction block would cause the transaction to neither commit nor rollback after its begin, effectively causing the transaction to remain open and leak into the next calls made to the connection and generating warnings: `WARNING:  there is already a transaction in progress`.
That's because `#transaction` used `rescue/else`, and the `else` block won't get executed in case of early break/return.
Here's the problem:
```
irb(main):001:1* def transaction
irb(main):002:1*   p 'pre'
irb(main):003:1*   yield
irb(main):004:1*   p 'post'
irb(main):005:1* rescue
irb(main):006:1*   p 'rescue'
irb(main):007:1* else
irb(main):008:1*   p 'else'
irb(main):009:1* ensure
irb(main):010:1*   p 'ensure'
irb(main):011:0> end
=> :transaction
irb(main):012:1* …
```
> Fix transaction leak on early break/return

- History.rdoc
- lib/pg/version.rb
As written in the release notes below, the changes since 1.3.5 are mostly bug fixes. However there are two new methods, which are necessary to implement #459 and which also affect the public API. Moreover the mere size of #459 is another reason to jump to 1.4.
@ged, @cbandy Do you think the same?
> Bump VERSION to 1.4.0

- lib/pg/connection.rb
This fixes the ruby 2.7 keyword warning again, after it was
reintroduced in 6d61d3de0ba0e8dae6d3c7dc783ab282495df8bb.
> Fix another ruby 2.7 keyword warning

- ext/pg_result.c
- spec/pg/result_spec.rb
> Extend the error message of PG::InvalidChangeOfResultFields to tell the number of fields

- ext/pg.c
- spec/pg/connection_spec.rb
* A dummy encoding does not understand JOHAB anyway.
* Creating an extra encoding leads to significant complexity and slowdowns
in Ruby implementations: https://bugs.ruby-lang.org/issues/18949
> Use Encoding::BINARY for JOHAB

- ext/pg_result.c
- lib/pg/version.rb
sequel_pg-1.16.0 introduced PQclear to fix a memory leek, but now a double free can happen, if there's an interrupt between PQclear and re-assiging a new PQresult. With this change the yielder can decide, if the result is cleared or not in the stream loop. In this case pgresult_clear() is called instead of PQclear, which avoids a double free.
This also raises the version to pg-1.4.4, so that sequel_pg can check for it.
Fixes #481
> Move PQclear to the result stream loop, to let sequel_pg use it

- Rakefile
- lib/pg/connection.rb
- spec/helpers.rb
- spec/pg/connection_async_spec.rb
- spec/pg/connection_spec.rb
- spec/pg/connection_sync_spec.rb
- spec/pg/scheduler_spec.rb
.. in favor of passing all hosts to libpq at once and instead adjust `connect_timeout` handling roughly to how libpq handles it.
See the commit messages for further description of the single changes.
Fixes #476
> Revert connecting on a host-by-host basis and make sure only authentication errors stop host iteration

- ext/pg.c
- ext/pg_connection.c
- lib/pg/connection.rb
- spec/pg/connection_spec.rb
This is one potential fix for #491.
Internally, libpq checks for null or empty string stored in pg_conn_host and falls back to the configured default `--with-pgport`. This does the same for our wrapper around [PQport](https://www.postgresql.org/docs/current/libpq-status.html#LIBPQ-PQPORT).
- https://github.com/postgres/postgres/blob/REL_15_0/src/interfaces/libpq/fe-connect.c#L1140-L1146
- https://github.com/postgres/postgres/blob/REL_15_0/src/interfaces/libpq/fe-connect.c#L2385-L2387
```c
/*
* Next, work out the port number corresponding to each host name.
*
* Note: unlike the above for host names, this could leave the port fields
* as null or empty strings.  We will substitute DEF_PGPORT whenever we
* read such a port field.
*/
```
```c
/* Figure out the port number we're going to use. …
```
> Return the libpq default port when blank in conninfo

- ext/pg_connection.c
- spec/pg/connection_spec.rb
This came up here: https://github.com/lsylvester/active_storage-postgresql/issues/16 It fails for me with the `unexpected response from server; first received character was "V"` in their test suite.
libpq's "lo_*" calls fail when a bigger amount of data is transferred and the connection is set to nonblocking mode. According to some discussion here
https://www.postgresql.org/message-id/20130606.082048.998330612674120762.t-ishii%40sraoss.co.jp
the large object interface isn't intended to be used with nonblocking mode.
It works to some extend with small data (< 8000 Bytes), but fails after lo_write of bigger data at the next exec call on the same connection like so:
```
message type 0x56 arrived from server while idle
message type 0x5a arrived from server while idle
message type 0x43 arrived …
```
> Disable nonblocking mode while large object calls

- .appveyor.yml
- .github/workflows/binary-gems.yml
- .github/workflows/source-gem.yml
- ext/pg_connection.c
- spec/helpers.rb
- spec/pg/connection_spec.rb
This PR updates CI on Appveyor and Github Actions and adds a test of the binary gems for x86-mingw32.
Adding the platform x86-mingw32 showed that there can be issues with `discard_results` getting into starvation under memory pressure. So the second half of commits improve `discard_results` behavior, documentation and specs.
> Update CI and improve `discard_results`

- lib/pg.rb
- lib/pg/connection.rb
- lib/pg/exceptions.rb
- spec/pg/connection_spec.rb
Make sure an error in put_copy_end doesn't lose the original exception.
Use a dedicated error class PG::LostCopyState for errors due to another query while COPYing and mention that it's probably due to another query. Previously the "no COPY in progress" PG::Error was less specific.
Remove transactions around the "another query" specs, previously the put_copy_data direction had a double fault due to another query while transaction is in error state.
Use discard_result which we have now and which does essentially what previous error handling did.
Cleanup temporary tables after running.
Move definition of error classes to exception.rb, where they better fit into.
> Improve copy_data error handling

- README.ja.md
- README.md
- spec/helpers.rb
- translation/po4a.cfg
`pg_config` is usually in the path of many distros, as soon as postgresql-client tools are installed, but server commands are not. That's why we always had to adjust the `PATH` accordingly. Determining the path of these commands automatically makes testing easier.
> Try to determine the path of PostgreSQL server commands from `pg_config`

- ext/pg_text_encoder.c
- lib/pg/basic_type_registry.rb
- spec/pg/basic_type_map_based_on_result_spec.rb
This encoder used to be excluded from the registry, since it's the only encoder that has a negative performance implication. However it should be there for completeness and because it's valuable for sending data per COPY command to the server.
Another issue was, that we supported PostgreSQL-8.4 to the time TextEncoder::Bytea was implemented, but the hex bytea format was introduced with PostgreSQL-9.0. Now we don't support such old versions any longer, so that the encoder can be used bar none.
> Add PG::TextEncoder::Bytea to BasicTypeRegistry

- ext/pg_result.c
- spec/pg/result_spec.rb
This ensures that the nfield-check doesn't hide errors like statement timeout.
Now the new PGresult is assigned to the streaming PG::Result, even if it has a different number of fields. This avoids leaking the memory of the wrong PGresult, but would lead to wrong fields or segfaults, if the PG::Result is used afterwards. Therefore the result is getting cleared before the raise.
Thanks to Neil Carvalho @neilvcarvalho for the test case!
Fixes #507
> Move nfields-check of stream-methods after result status check

- lib/pg/binary_decoder/timestamp.rb
- lib/pg/binary_encoder/timestamp.rb
- lib/pg/coder.rb
- lib/pg/text_decoder/timestamp.rb
- spec/pg/type_spec.rb
This re-enables initialization per Hash, which was removed in commit fd8bdbbcd0f270e1368a4a56bf6781494e96f1d7
Also add deprecation warning about Hash arguments like: 
```ruby
PG::Coder.new(hash) is deprecated. Please use keyword arguments instead! Called from [...]gems/activerecord-6.1.7.3/lib/active_record/connection_adapters/postgresql_adapter.rb:883:in `new'
```
> Fix regression that PG::Coder derivates can only be initialized by keyword arguments

- ext/pg.h
- ext/pg_connection.c
... to avoid shared gobal state.
The registered callback is stored per connection in libpq anyway, so that it makes sense to store the default also per connection.
> Move the default_notice_receiver to connection struct

- ext/pg_coder.c
- ext/pg_connection.c
- ext/pg_copy_coder.c
- ext/pg_record_coder.c
- ext/pg_result.c
- ext/pg_tuple.c
- ext/pg_type_map.c
- ext/pg_type_map_all_strings.c
- ext/pg_type_map_by_class.c
- ext/pg_type_map_by_column.c
- ext/pg_type_map_by_oid.c
- ext/pg_type_map_in_ruby.c
Write barrier protected objects are allowed to be promoted to the old generation, which means they only get marked on major GC. The downside is that the RB_BJ_WRITE macro MUST be used to set references, otherwise the referenced object may be garbaged collected.
> Add write barriers to PG classes

- ext/pg_connection.c
- lib/pg/connection.rb
- spec/pg/connection_spec.rb
... without data exchange with the server.
Related to #509
> Add PG::Connection#check_connection as a way to verify the socket is OK

- lib/pg/binary_decoder/timestamp.rb
- lib/pg/binary_encoder/timestamp.rb
- lib/pg/text_decoder/timestamp.rb
- spec/pg/type_spec.rb
It is unexpected, since it makes the coder behave contrary to the class name. Moreover it causes a regression in rails:
https://github.com/rails/rails/issues/48049
Fixes #524
> Don't overwrite flags of timestamp coders

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
... when not using an coder.
To keep compatibility the handling of header and trailer data is now only done when a coder is given.
Fixes #526
> Fix regression in copy_data regarding binary format

- lib/pg/binary_decoder/timestamp.rb
- lib/pg/binary_encoder/timestamp.rb
- lib/pg/coder.rb
- lib/pg/text_decoder/timestamp.rb
- spec/pg/type_spec.rb
See https://github.com/ged/ruby-pg/issues/523
See https://ruby-doc.org/3.2.2/Warning.html
See https://bugs.ruby-lang.org/issues/17000
The deprecation warning about `PG::Coder.new(hash)` introduced in v1.5.0 is so frequently reported that it would be more useful if a user had better control over the warning.
This PR sets the category for deprecation warnings. Setting `category: :deprecated` will only show warnings to users who either set `Warning[:deprecated] = true` or set `RUBYOPT=-W:deprecated`. `Warning[:deprecated] = false` by default since Ruby 2.7.2, so it suppresses the warning for most users.
> Add category to deprecation warnings

- lib/pg.rb
Avoid error "uninitialized constant Truffle::WarningOperations" on Truffleruby up to 22.3.1
The error was triggered by adding the :deprecation category in #528
> Fix error on warn with category on Truffleruby

- ext/pg_result.c
- ext/pg_type_map_by_column.c
Initialize connection and typemap prior to any object allocations, to make sure valid objects are marked.
This regression was introduced in commit 5061020c28d694464a5fa5474062d8486912daa1 while introducing write barriers. However it is not necessary to use `RB_OBJ_WRITE` when the "old" object (1st argument) is not yet created or immediately after it was created. The initial assignment can and must be done before processing the typemap as it was before the above commit.
Fixes #530
> Fix possible segfault when creating new PG::Result

- ext/pg_connection.c
This PR reintroduces a call to `pgconn_set_internal_encoding_index` in `pgconn_set_default_encoding`. This call was removed in version `1.3.0` (specifically in this [PR](https://github.com/ged/ruby-pg/pull/397)).
When `Encoding.default_internal` is set, ruby-pg sends a `SET client_encoding TO ...` query, if that query succeeds everything works great. If it fails and the connection is closed, well nothing breaks. 
Now assuming Ruby and Postgres are both using UTF-8 encoding, if that query fails AND the connection remains open, we end up with desynchronized encoding between Ruby and Ruby-pg where Ruby's encoding is UTF-8, Postgres Encoding is UTF-8 but Ruby-pg falls back to `SQL_ASCII` (I think?) causing it to encode the incoming UTF-8 strings from Postgres into ASCII.
Version `1.2.3` …
> Call pgconn_set_internal_encoding_index in all branches of pgconn_set_default_encoding

- ext/pg_connection.c
- spec/pg/connection_spec.rb
It is important for connection proxies, who disallow configuration settings.
This PR is an alternative to #542. In addition it adds a test case.
Closes #542
> Don't set the server's client_encoding if it's unnecessary

- ext/extconf.rb
This PR fixes compiling the pg extension with MSVC 2022 when using extconf.rb, nmake and libpq installed by vcpkg (not mingw64).
Running the command:
ruby extconf.rb --without-pg-config --with-pg-include=c:\Source\vcpkg\installed\x64-windows\include --with-pg-lib=c:\Source\vcpkg\installed\x64-windows\lib
Fails with linker errors:
pg_connection.obj : error LNK2019: unresolved external symbol __imp_WSAGetLastError referenced in function pg_rb_thread_io_wait
This is fixed by adding ws2_32.lib to the linker command.
Not sure I am adding the extra library in the best place (or the correct way), but this does fix the issue for me.
> Fix MSVC 2022 Compilation

- ext/pg_binary_encoder.c
Timespec fields' time_t type is not guaranteed to be any particular integer. Tests with binary timestamp conversion are failing on 32bit arches (e.g. intel x86) until they are retyped into int64_t, which fixes the issue with encoding the Time instances.
Decoder doesn't need adjusting. It returns the correct time from the encoded binary representation.
Resolves: https://github.com/ged/ruby-pg/issues/545
> Explicitly retype timespec fields to int64_t to fix compatibility with 32bit arches.

- ext/pg_copy_coder.c
> Fix BinaryEncoder::Timestamp and possible buffer overflows on 32 bit platforms 

- pg.gemspec
README.md is already translated when it reaches the gem form, no need to ship the files for translation.
> Don't ship POT files in gem.

- ext/pg_connection.c
- lib/pg/connection.rb
- spec/helpers.rb
- spec/pg/connection_spec.rb
libpq resolves the host address while PQreset, but ruby-pg doesn't. This is because we explicit set the `hostaddr` connection parameter when the connection is established the first time. This prevents a newly DNS resolution when running PQresetStart.
This patch adds DNS resolution to `conn.reset`
Since we can not change the connection parameters after connection start, the underlying PGconn pointer is exchanged in reset_start2. This is done by a PQfinish() + PQconnectStart() sequence. That way the `hostaddr` parameter is updated and a new connection is established with it.
There is a `/etc/hosts` and `sudo` based test in the specs.
The behavior of libpq is slightly different to that of ruby-pg.
It can be verified by the following code:
```ruby
require "pg"
puts "pg version: …
```
> Renew address resolution in conn.reset

- ext/extconf.rb
- ext/pg_connection.c
Direct access is disallowed since ruby-3.4. And the preferred function `rb_io_descriptor`is available since ruby-3.1.
> Remove deprecated use of fptr->fd

- ext/pg_connection.c
ext/pg_connection.c:38:1: warning: function 'pg_raise_conn_error' could be declared with attribute 'noreturn' [-Wmissing-noreturn]
> Avoid compiler warning

- ext/pg_connection.c
- spec/pg/connection_spec.rb
Make `pgconn_connect_poll` close the socket prior to calling `PQconnectPoll`
Since `PQconnectPoll` can change the underlying socket and thus the file descriptor, closing the socket after can manifest a race condition where libpq has closed the socket and another thread has opened a socket with the recycled file descriptor. When the original socket is closed from Ruby, the VM will notify the new thread that the FD has closed (erroneously) resulting in an exception.
This is an exception I encountered in a production environment (C Ruby 3.3), somewhat sporadically  It is quite misleading as the way this manifests is that the exception raises [while waiting](https://github.com/ged/ruby-pg/blob/master/lib/pg/connection.rb#L674) on the socket, so it seems as if connections are getting shared …
> Make `pgconn_connect_poll` close the socket prior to calling `PQconnectPoll`

- lib/pg/connection.rb
- lib/pg/exceptions.rb
- spec/pg/connection_spec.rb
Like in rails: https://api.rubyonrails.org/classes/ActiveRecord/Rollback.html
> Add PG::RollbackTransaction as an option to exit conn.transaction

- ext/pg_text_decoder.c
- ext/pg_text_encoder.c
- lib/pg.rb
- lib/pg/basic_type_map_for_queries.rb
- lib/pg/basic_type_registry.rb
- spec/helpers.rb
Ruby-3.4+ prints a warning, if bigdecimal is required but not in the Gemfile. But it's a false positive, since we enable bigdecimal depending features only if it's available. And most people don't need these features.
Fixes #569
> Don't print a warning when bigdecimal is required on ruby-3.4+

- .appveyor.yml
It failed with:
Command executed with exception: error: target not found: mingw-w64-i686-postgresql
> CI: Fix appveyor build by switching to x64 platform

- spec/helpers.rb
- spec/pg/connection_spec.rb
This is important if RUBY_PG_TEST_DIR is set to a different directory.
Fixes #576
> Adjust tests with dedicated ssl certificate to fetch it from the test directory

- lib/pg/basic_type_registry.rb
- spec/pg/basic_type_map_for_results_spec.rb
The PostgreSQL server just sends the generic OID 2249 for generic record/composite types in query results like:
```SQL
SELECT row(123, 'str', true, null)
```
Since we don't get the OIDs of the record items, we can not properly decode them. Nevertheless it's helpful to decode at least with the default type map and decode all items to an array of strings like so:
```ruby
c.exec("SELECT 6, row(123, 'str', true, null), 7").values
=> [[6, ["123", "str", "t", nil], 7]]
```
instead of:
```ruby
=> [[6, "(123,str,t,)", 7]] 
```
Related to #578
> Add default decoder for anonymous record types to BasicTypeRegistry

- ext/pg_connection.c
- lib/pg/connection.rb
- spec/helpers.rb
- spec/pg/connection_async_spec.rb
- spec/pg/connection_spec.rb
Commit 016c17c9c9bbc51bf5fab2087ad485367c789118 introduced a regression, that leads to a host list duplication every time `conn.reset` is used.
Since the hosts are duplicated when resolve_hosts is called, the `conn.coninfo_hash` can not be used. So the fix is to store the original hash of connection options for later use in conn.reset .
Fixes #586
> Save connection options for conn.reset

- lib/pg/connection.rb
- spec/pg/connection_spec.rb
This will be removed in libpq of PostgreSQL-17 by this commit:
https://github.com/postgres/postgres/commit/105024a47238e33647d346264b4f6fe68a7287ed
The adjustment of connect_timeout from 1 to 2 seconds was anyway only relevant due to libpq's internal rounding, which doesn't apply to ruby.
> Remove raising conect_timeout from 1 to 2 seconds

- pg.gemspec
Security inspection of some users or even their clients can be confused by finding out unknown YAML files with `Download` instructions inside final production releases. We can just get rid of them.
Also Regex is fixed now, `/` before closing `)` was breaking.
> Exclude CI files from built gem

- .gitignore
It's an artifact after `rake test`, and should not be tracked by git.
> Ignore `test_trace.out` file for git

- lib/pg/connection.rb
- spec/pg/basic_type_map_based_on_result_spec.rb
- spec/pg/connection_spec.rb
Fixes https://github.com/ged/ruby-pg/issues/594
> Fix binary copy_data in Ractor context

- Rakefile.cross
- spec/pg/connection_spec.rb
This is disabled by default due to the `-static` option. The `thread` doesn't work with `-static`, that's why it is enabled by `-DOPENSSL_THREADS`. The thread functions are used in libcrypto.a and libssl.a but only defined in libssl.a.
Fixes #595
> Enable thread safety in static OpenSSL build

- Rakefile.cross
They seem to be no longer necessary.
> Remove workarounds for PostgreSQL static build

- README.md
- ext/pg_binary_decoder.c
- ext/pg_binary_encoder.c
- lib/pg/basic_type_registry.rb
- spec/pg/basic_type_map_based_on_result_spec.rb
- spec/pg/basic_type_map_for_results_spec.rb
- spec/pg/type_spec.rb
> Add PG::BinaryDecoder::Array and PG::BinaryEncoder::Array

- spec/helpers.rb
- spec/helpers/tcp_gate_scheduler.rb
3 tests failed after upgrade to Linux-6.10 due to starvation of data transfer in write direction. This was because we stopped the transfer when less than the requested size could be read. Stopping only when no data at all was read fixes this issue.
It also turned out, that the same issue led to starvation of SSL encrypted traffix. So this patch re-enables SSL for scheduler tests which was disabled in commit f270b714c66690b18a0e28bf0af667212cb00bee
Fixes #601
> Fix writing lots of data through the TcpGateScheduler

- ext/pg_coder.c
- ext/pg_connection.c
- ext/pg_text_encoder.c
It is no good practice to put uninitialized VALUEs into ruby array and it can lead to C/Java exceptions in Truffleruby. So better initialize them to nil.
Also remove the GC_GUARD, since it's not necessary.
> Initialize "intermediate" VALUE for encoding

- .github/workflows/binary-gems.yml
- .github/workflows/source-gem.yml
- ext/gvl_wrappers.c
- ext/gvl_wrappers.h
- ext/pg_connection.c
- lib/pg/connection.rb
- spec/pg/connection_spec.rb
- spec/pg/scheduler_spec.rb
Also make `pipeline_sync` an alias for `sync_pipeline_sync` vs. `async_pipeline_sync`.
Now `send_pipeline_sync` and `flush` is used to notify IO waiting to the scheduler.
> Add Connection#send_pipeline_sync, async_pipeline_sync and release GVL at PQ(sendP|p)ipelineSync

- ext/pg_type_map_by_column.c
- spec/pg/type_map_by_column_spec.rb
This could cause a segfault.
Fixes #620
> Verify array input to PG::TypeMapByColumn

- ext/pg.h
- ext/pg_binary_encoder.c
- ext/pg_coder.c
- ext/pg_text_encoder.c
- lib/pg/coder.rb
- spec/pg/type_spec.rb
Setting dimensions is especially useful, when a Record shall be encoded into an Array, since the Array encoder can not distinguish if the array shall be encoded as a higher dimension or as a record otherwise.
Related to #620
> Add possibility to define the number of array dimensions to be encoded

- .appveyor.yml
- pg.gemspec
There is no package with contains libpq only, but the postgresql package now has less depencies than it had in the past. Especially python and perl are optional dependecies now, so that the install size is acceptable:
```
Pakete (5) mingw-w64-clang-aarch64-icu-75.1-2  mingw-w64-clang-aarch64-lz4-1.10.0-1
mingw-w64-clang-aarch64-openssl-3.4.0-1  winpty-0.4.3-3  mingw-w64-clang-aarch64-postgresql-17.2-1
Gesamtgröße des Downloads:              40,09 MiB
Gesamtgröße der installierten Pakete:  198,79 MiB
```
> Add MINGW package dependency which is resolved by RubyInstaller

- spec/pg/connection_spec.rb
The function `PQescapeString` was changed in PostgreSQL 17.4, 16.8, 15.12, 14.17, and 13.20. It now returns a predefined invalid character as a replacement in the connection encoding, if the input text is not valid according to the current connection encoding. Using a compatible connection encoding avoids this, so that we get the original text out of the singleton escape function.
Fixes #628
> Use a connection encoding compatible to "Möhre"

- ext/pg_connection.c
- spec/pg/connection_spec.rb
Ref: https://github.com/rails/rails/issues/54712
Returning 0 on error is a bit uncommon in Ruby, and not very convenient, I think it would make more sense to raise the appropriate exception.
Now I understand that this is a bit of a breaking change, so I'd understand why you wouldn't want to merge this.
cc @joshuay03
> Change #server_version to raise instead of return 0 on error

- spec/helpers.rb
- spec/pg/connection_spec.rb
54321 is an ephemeral port on most operating systems, so that is's sometimes already in use in CI. This makes initdb fail sometimes on Windows like so:
```
Success. You can now start the database server using:
"D:\a\ruby-pg\ruby-pg\pgsql\bin\pg_ctl" -D D:/a/ruby-pg/ruby-pg/tmp_test_specs/data -l logfile start
waiting for server to start....2025-03-09 16:03:40.843 UTC [4624] LOG:  starting PostgreSQL 17.0 on x86_64-windows, compiled by msvc-19.41.34120, 64-bit
2025-03-09 16:03:40.846 UTC [4624] LOG:  could not bind IPv6 address "::1": Permission denied
2025-03-09 16:03:40.846 UTC [4624] LOG:  could not bind IPv4 address "127.0.0.1": Permission denied
2025-03-09 16:03:40.846 UTC [4624] WARNING:  could not create listen socket for "localhost"
2025-03-09 16:03:40.846 UTC [4624] FATAL:  could …
```
> Avoid usage of port 54321 for tests but use 23456

- Rakefile
- ext/extconf.rb
- ports/patches/openssl/3.4.0/0001-aarch64-mingw.patch
- ports/patches/postgresql/17.2/0001-Use-workaround-of-__builtin_setjmp-only-on-MINGW-on-.patch
This adds rake target `rake gem:native:aarch64-mingw-ucrt`.
It needs rake-compiler-dock with support for Windows on Arm64, introduced in: https://github.com/rake-compiler/rake-compiler-dock/pull/152
Patches submitted:
* Postgresql: https://commitfest.postgresql.org/patch/5610/
* OpenSSL: https://github.com/openssl/openssl/pull/26605
> Add cross compiler for aarch64-mingw-ucrt

- lib/pg/basic_type_map_for_queries.rb
This was broken since ruby commit https://github.com/ruby/ruby/commit/d80f3a287c5c8d0404b6cb837db360cab320cde1 .
It shrinked shareability of `Proc` objects, so that we need to avoid a `Proc` here.
> Fix making PG::BasicTypeMapForQueries shareable for Ractor

- Rakefile
It was added to rake-compiler-dock in https://github.com/rake-compiler/rake-compiler-dock/pull/155 .
This PR can be merged when rake-compiler-dock.1.10 is released and updated in pg's Gemfile.
> Remove installation of Macos "mig" tool

- lib/pg/coder.rb
- spec/pg/type_spec.rb
This fixes the compatibility to pg-1.5.9, when deserializing Marshal data from pg-1.6, as long as the new attribute isn't used.
Fixes #652
> Serialize CompositeCoder#dimensions only when set

- lib/pg.rb
- lib/pg/version.rb
- spec/pg_spec.rb
Freeze some constants to make them available in a Ractor context.
> Fix some constants to be frozen and usable in a Ractor

- Rakefile
- ext/extconf.rb
There are several absolute paths built into the binary. For instance fallback path to `pg_service.conf` or the fallback path to kerberos ccache file or the rpath included into the libpq or C-ext files.
They can be avoided or fixed by disabling rpaths and by using `DESTDIR` instead of `--prefix` configure option.
Fixes #666
The remaining rpath to libruby will probably be fixed by: https://github.com/rake-compiler/rake-compiler-dock/pull/165
Also fix the `MAKEFLAGS` option. `MAKEOPTS` was wrong.
> Remove absolute paths from binaries which point to build directories

- ext/extconf.rb
- ext/pg.h
- ext/pg_connection.c
- ext/pg_result.c
- ext/pg_tuple.c
- spec/pg/result_spec.rb
- spec/pg/tuple_spec.rb
Multiple Ractor instances could otherwise initialize them simultanly, leading to data races.
> PG::Result: Initialize all on-demand values before freeze
